// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="filtr_Gauss,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=9.400000,HLS_SYN_LAT=927931,HLS_SYN_TPT=927929,HLS_SYN_MEM=2,HLS_SYN_DSP=5,HLS_SYN_FF=688,HLS_SYN_LUT=1363,HLS_VERSION=2018_3}" *)

module filtr_Gauss (
        in_r_TDATA,
        in_r_TKEEP,
        in_r_TSTRB,
        in_r_TUSER,
        in_r_TLAST,
        in_r_TID,
        in_r_TDEST,
        out_r_TDATA,
        out_r_TKEEP,
        out_r_TSTRB,
        out_r_TUSER,
        out_r_TLAST,
        out_r_TID,
        out_r_TDEST,
        ap_clk,
        ap_rst_n,
        in_r_TVALID,
        in_r_TREADY,
        ap_start,
        out_r_TVALID,
        out_r_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [7:0] in_r_TDATA;
input  [0:0] in_r_TKEEP;
input  [0:0] in_r_TSTRB;
input  [0:0] in_r_TUSER;
input  [0:0] in_r_TLAST;
input  [0:0] in_r_TID;
input  [0:0] in_r_TDEST;
output  [7:0] out_r_TDATA;
output  [0:0] out_r_TKEEP;
output  [0:0] out_r_TSTRB;
output  [0:0] out_r_TUSER;
output  [0:0] out_r_TLAST;
output  [0:0] out_r_TID;
output  [0:0] out_r_TDEST;
input   ap_clk;
input   ap_rst_n;
input   in_r_TVALID;
output   in_r_TREADY;
input   ap_start;
output   out_r_TVALID;
input   out_r_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    AXIvideo2Mat_U0_ap_start;
wire    AXIvideo2Mat_U0_ap_done;
wire    AXIvideo2Mat_U0_ap_continue;
wire    AXIvideo2Mat_U0_ap_idle;
wire    AXIvideo2Mat_U0_ap_ready;
wire    AXIvideo2Mat_U0_start_out;
wire    AXIvideo2Mat_U0_start_write;
wire    AXIvideo2Mat_U0_in_r_TREADY;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_V_write;
wire    rozmycie_U0_ap_start;
wire    rozmycie_U0_ap_done;
wire    rozmycie_U0_ap_continue;
wire    rozmycie_U0_ap_idle;
wire    rozmycie_U0_ap_ready;
wire    rozmycie_U0_start_out;
wire    rozmycie_U0_start_write;
wire    rozmycie_U0_img_in_data_stream_V_read;
wire   [7:0] rozmycie_U0_img_out_data_stream_V_din;
wire    rozmycie_U0_img_out_data_stream_V_write;
wire    Mat2AXIvideo_U0_ap_start;
wire    Mat2AXIvideo_U0_ap_done;
wire    Mat2AXIvideo_U0_ap_continue;
wire    Mat2AXIvideo_U0_ap_idle;
wire    Mat2AXIvideo_U0_ap_ready;
wire    Mat2AXIvideo_U0_img_data_stream_V_read;
wire   [7:0] Mat2AXIvideo_U0_out_r_TDATA;
wire    Mat2AXIvideo_U0_out_r_TVALID;
wire   [0:0] Mat2AXIvideo_U0_out_r_TKEEP;
wire   [0:0] Mat2AXIvideo_U0_out_r_TSTRB;
wire   [0:0] Mat2AXIvideo_U0_out_r_TUSER;
wire   [0:0] Mat2AXIvideo_U0_out_r_TLAST;
wire   [0:0] Mat2AXIvideo_U0_out_r_TID;
wire   [0:0] Mat2AXIvideo_U0_out_r_TDEST;
wire    ap_sync_continue;
wire    instance_in_data_str_full_n;
wire   [7:0] instance_in_data_str_dout;
wire    instance_in_data_str_empty_n;
wire    instance_out_data_st_full_n;
wire   [7:0] instance_out_data_st_dout;
wire    instance_out_data_st_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_rozmycie_U0_din;
wire    start_for_rozmycie_U0_full_n;
wire   [0:0] start_for_rozmycie_U0_dout;
wire    start_for_rozmycie_U0_empty_n;
wire   [0:0] start_for_Mat2AXIvideo_U0_din;
wire    start_for_Mat2AXIvideo_U0_full_n;
wire   [0:0] start_for_Mat2AXIvideo_U0_dout;
wire    start_for_Mat2AXIvideo_U0_empty_n;
wire    Mat2AXIvideo_U0_start_full_n;
wire    Mat2AXIvideo_U0_start_write;

AXIvideo2Mat AXIvideo2Mat_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2Mat_U0_ap_start),
    .start_full_n(start_for_rozmycie_U0_full_n),
    .ap_done(AXIvideo2Mat_U0_ap_done),
    .ap_continue(AXIvideo2Mat_U0_ap_continue),
    .ap_idle(AXIvideo2Mat_U0_ap_idle),
    .ap_ready(AXIvideo2Mat_U0_ap_ready),
    .start_out(AXIvideo2Mat_U0_start_out),
    .start_write(AXIvideo2Mat_U0_start_write),
    .in_r_TDATA(in_r_TDATA),
    .in_r_TVALID(in_r_TVALID),
    .in_r_TREADY(AXIvideo2Mat_U0_in_r_TREADY),
    .in_r_TKEEP(in_r_TKEEP),
    .in_r_TSTRB(in_r_TSTRB),
    .in_r_TUSER(in_r_TUSER),
    .in_r_TLAST(in_r_TLAST),
    .in_r_TID(in_r_TID),
    .in_r_TDEST(in_r_TDEST),
    .img_data_stream_V_din(AXIvideo2Mat_U0_img_data_stream_V_din),
    .img_data_stream_V_full_n(instance_in_data_str_full_n),
    .img_data_stream_V_write(AXIvideo2Mat_U0_img_data_stream_V_write)
);

rozmycie rozmycie_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(rozmycie_U0_ap_start),
    .start_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .ap_done(rozmycie_U0_ap_done),
    .ap_continue(rozmycie_U0_ap_continue),
    .ap_idle(rozmycie_U0_ap_idle),
    .ap_ready(rozmycie_U0_ap_ready),
    .start_out(rozmycie_U0_start_out),
    .start_write(rozmycie_U0_start_write),
    .img_in_data_stream_V_dout(instance_in_data_str_dout),
    .img_in_data_stream_V_empty_n(instance_in_data_str_empty_n),
    .img_in_data_stream_V_read(rozmycie_U0_img_in_data_stream_V_read),
    .img_out_data_stream_V_din(rozmycie_U0_img_out_data_stream_V_din),
    .img_out_data_stream_V_full_n(instance_out_data_st_full_n),
    .img_out_data_stream_V_write(rozmycie_U0_img_out_data_stream_V_write)
);

Mat2AXIvideo Mat2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Mat2AXIvideo_U0_ap_start),
    .ap_done(Mat2AXIvideo_U0_ap_done),
    .ap_continue(Mat2AXIvideo_U0_ap_continue),
    .ap_idle(Mat2AXIvideo_U0_ap_idle),
    .ap_ready(Mat2AXIvideo_U0_ap_ready),
    .img_data_stream_V_dout(instance_out_data_st_dout),
    .img_data_stream_V_empty_n(instance_out_data_st_empty_n),
    .img_data_stream_V_read(Mat2AXIvideo_U0_img_data_stream_V_read),
    .out_r_TDATA(Mat2AXIvideo_U0_out_r_TDATA),
    .out_r_TVALID(Mat2AXIvideo_U0_out_r_TVALID),
    .out_r_TREADY(out_r_TREADY),
    .out_r_TKEEP(Mat2AXIvideo_U0_out_r_TKEEP),
    .out_r_TSTRB(Mat2AXIvideo_U0_out_r_TSTRB),
    .out_r_TUSER(Mat2AXIvideo_U0_out_r_TUSER),
    .out_r_TLAST(Mat2AXIvideo_U0_out_r_TLAST),
    .out_r_TID(Mat2AXIvideo_U0_out_r_TID),
    .out_r_TDEST(Mat2AXIvideo_U0_out_r_TDEST)
);

fifo_w8_d2_A instance_in_data_str_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_V_din),
    .if_full_n(instance_in_data_str_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_V_write),
    .if_dout(instance_in_data_str_dout),
    .if_empty_n(instance_in_data_str_empty_n),
    .if_read(rozmycie_U0_img_in_data_stream_V_read)
);

fifo_w8_d2_A instance_out_data_st_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(rozmycie_U0_img_out_data_stream_V_din),
    .if_full_n(instance_out_data_st_full_n),
    .if_write(rozmycie_U0_img_out_data_stream_V_write),
    .if_dout(instance_out_data_st_dout),
    .if_empty_n(instance_out_data_st_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_V_read)
);

start_for_rozmycie_U0 start_for_rozmycie_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_rozmycie_U0_din),
    .if_full_n(start_for_rozmycie_U0_full_n),
    .if_write(AXIvideo2Mat_U0_start_write),
    .if_dout(start_for_rozmycie_U0_dout),
    .if_empty_n(start_for_rozmycie_U0_empty_n),
    .if_read(rozmycie_U0_ap_ready)
);

start_for_Mat2AXIvideo_U0 start_for_Mat2AXIvideo_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Mat2AXIvideo_U0_din),
    .if_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .if_write(rozmycie_U0_start_write),
    .if_dout(start_for_Mat2AXIvideo_U0_dout),
    .if_empty_n(start_for_Mat2AXIvideo_U0_empty_n),
    .if_read(Mat2AXIvideo_U0_ap_ready)
);

assign AXIvideo2Mat_U0_ap_continue = 1'b1;

assign AXIvideo2Mat_U0_ap_start = ap_start;

assign Mat2AXIvideo_U0_ap_continue = 1'b1;

assign Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n;

assign Mat2AXIvideo_U0_start_full_n = 1'b1;

assign Mat2AXIvideo_U0_start_write = 1'b0;

assign ap_done = Mat2AXIvideo_U0_ap_done;

assign ap_idle = (rozmycie_U0_ap_idle & Mat2AXIvideo_U0_ap_idle & AXIvideo2Mat_U0_ap_idle);

assign ap_ready = AXIvideo2Mat_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Mat2AXIvideo_U0_ap_done;

assign ap_sync_ready = AXIvideo2Mat_U0_ap_ready;

assign in_r_TREADY = AXIvideo2Mat_U0_in_r_TREADY;

assign out_r_TDATA = Mat2AXIvideo_U0_out_r_TDATA;

assign out_r_TDEST = Mat2AXIvideo_U0_out_r_TDEST;

assign out_r_TID = Mat2AXIvideo_U0_out_r_TID;

assign out_r_TKEEP = Mat2AXIvideo_U0_out_r_TKEEP;

assign out_r_TLAST = Mat2AXIvideo_U0_out_r_TLAST;

assign out_r_TSTRB = Mat2AXIvideo_U0_out_r_TSTRB;

assign out_r_TUSER = Mat2AXIvideo_U0_out_r_TUSER;

assign out_r_TVALID = Mat2AXIvideo_U0_out_r_TVALID;

assign rozmycie_U0_ap_continue = 1'b1;

assign rozmycie_U0_ap_start = start_for_rozmycie_U0_empty_n;

assign start_for_Mat2AXIvideo_U0_din = 1'b1;

assign start_for_rozmycie_U0_din = 1'b1;

endmodule //filtr_Gauss
