// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "rozmycie.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic rozmycie::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic rozmycie::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> rozmycie::ap_ST_fsm_state1 = "1";
const sc_lv<4> rozmycie::ap_ST_fsm_state2 = "10";
const sc_lv<4> rozmycie::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> rozmycie::ap_ST_fsm_state8 = "1000";
const bool rozmycie::ap_const_boolean_1 = true;
const sc_lv<32> rozmycie::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> rozmycie::ap_const_lv32_2 = "10";
const bool rozmycie::ap_const_boolean_0 = false;
const sc_lv<1> rozmycie::ap_const_lv1_1 = "1";
const sc_lv<32> rozmycie::ap_const_lv32_1 = "1";
const sc_lv<1> rozmycie::ap_const_lv1_0 = "0";
const sc_lv<10> rozmycie::ap_const_lv10_0 = "0000000000";
const sc_lv<32> rozmycie::ap_const_lv32_3 = "11";
const sc_lv<11> rozmycie::ap_const_lv11_0 = "00000000000";
const sc_lv<10> rozmycie::ap_const_lv10_2D1 = "1011010001";
const sc_lv<10> rozmycie::ap_const_lv10_1 = "1";
const sc_lv<10> rozmycie::ap_const_lv10_2D0 = "1011010000";
const sc_lv<32> rozmycie::ap_const_lv32_9 = "1001";
const sc_lv<9> rozmycie::ap_const_lv9_0 = "000000000";
const sc_lv<11> rozmycie::ap_const_lv11_501 = "10100000001";
const sc_lv<11> rozmycie::ap_const_lv11_1 = "1";
const sc_lv<11> rozmycie::ap_const_lv11_500 = "10100000000";
const sc_lv<32> rozmycie::ap_const_lv32_A = "1010";
const sc_lv<5> rozmycie::ap_const_lv5_0 = "00000";
const sc_lv<32> rozmycie::ap_const_lv32_8 = "1000";
const sc_lv<32> rozmycie::ap_const_lv32_F = "1111";
const sc_lv<8> rozmycie::ap_const_lv8_0 = "00000000";
const sc_lv<14> rozmycie::ap_const_lv14_13 = "10011";
const sc_lv<15> rozmycie::ap_const_lv15_34 = "110100";

rozmycie::rozmycie(sc_module_name name) : sc_module(name), mVcdFile(0) {
    buffer_val_0_U = new rozmycie_buffer_val_0("buffer_val_0_U");
    buffer_val_0_U->clk(ap_clk);
    buffer_val_0_U->reset(ap_rst);
    buffer_val_0_U->address0(buffer_val_0_address0);
    buffer_val_0_U->ce0(buffer_val_0_ce0);
    buffer_val_0_U->q0(buffer_val_0_q0);
    buffer_val_0_U->address1(buffer_val_0_addr_reg_744);
    buffer_val_0_U->ce1(buffer_val_0_ce1);
    buffer_val_0_U->we1(buffer_val_0_we1);
    buffer_val_0_U->d1(img_in_data_stream_V_dout);
    buffer_val_1_U = new rozmycie_buffer_val_0("buffer_val_1_U");
    buffer_val_1_U->clk(ap_clk);
    buffer_val_1_U->reset(ap_rst);
    buffer_val_1_U->address0(buffer_val_1_address0);
    buffer_val_1_U->ce0(buffer_val_1_ce0);
    buffer_val_1_U->q0(buffer_val_1_q0);
    buffer_val_1_U->address1(buffer_val_1_addr_reg_738);
    buffer_val_1_U->ce1(buffer_val_1_ce1);
    buffer_val_1_U->we1(buffer_val_1_we1);
    buffer_val_1_U->d1(buffer_val_0_q0);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U9 = new filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1<1,1,6,8,14,14>("filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U9");
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U9->din0(grp_fu_599_p0);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U9->din1(grp_fu_599_p1);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U9->din2(grp_fu_599_p2);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U9->dout(grp_fu_599_p3);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U10 = new filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1<1,1,6,8,14,14>("filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U10");
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U10->din0(grp_fu_607_p0);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U10->din1(grp_fu_607_p1);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U10->din2(grp_fu_607_p2);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U10->dout(grp_fu_607_p3);
    filtr_Gauss_mac_muladd_7ns_8ns_14ns_15_1_1_U11 = new filtr_Gauss_mac_muladd_7ns_8ns_14ns_15_1_1<1,1,7,8,14,15>("filtr_Gauss_mac_muladd_7ns_8ns_14ns_15_1_1_U11");
    filtr_Gauss_mac_muladd_7ns_8ns_14ns_15_1_1_U11->din0(grp_fu_615_p0);
    filtr_Gauss_mac_muladd_7ns_8ns_14ns_15_1_1_U11->din1(grp_fu_615_p1);
    filtr_Gauss_mac_muladd_7ns_8ns_14ns_15_1_1_U11->din2(grp_fu_615_p2);
    filtr_Gauss_mac_muladd_7ns_8ns_14ns_15_1_1_U11->dout(grp_fu_615_p3);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_15_1_1_U12 = new filtr_Gauss_mac_muladd_6ns_8ns_14ns_15_1_1<1,1,6,8,14,15>("filtr_Gauss_mac_muladd_6ns_8ns_14ns_15_1_1_U12");
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_15_1_1_U12->din0(grp_fu_623_p0);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_15_1_1_U12->din1(grp_fu_623_p1);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_15_1_1_U12->din2(grp_fu_623_p2);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_15_1_1_U12->dout(grp_fu_623_p3);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U13 = new filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1<1,1,6,8,14,14>("filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U13");
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U13->din0(grp_fu_631_p0);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U13->din1(grp_fu_631_p1);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U13->din2(grp_fu_631_p2);
    filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U13->dout(grp_fu_631_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_V_2_2_i_fu_575_p2);
    sensitive << ( tmp5_cast_fu_559_p1 );
    sensitive << ( tmp8_fu_569_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( img_in_data_stream_V_empty_n );
    sensitive << ( img_out_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( or_cond6_reg_755_pp0_iter3_reg );
    sensitive << ( ap_predicate_op64_read_state4 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( img_in_data_stream_V_empty_n );
    sensitive << ( img_out_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( or_cond6_reg_755_pp0_iter3_reg );
    sensitive << ( ap_predicate_op64_read_state4 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( img_in_data_stream_V_empty_n );
    sensitive << ( img_out_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( or_cond6_reg_755_pp0_iter3_reg );
    sensitive << ( ap_predicate_op64_read_state4 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( img_in_data_stream_V_empty_n );
    sensitive << ( ap_predicate_op64_read_state4 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter4);
    sensitive << ( img_out_data_stream_V_full_n );
    sensitive << ( or_cond6_reg_755_pp0_iter3_reg );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( exitcond_fu_249_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond3_fu_209_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_predicate_op64_read_state4);
    sensitive << ( tmp_4_reg_730 );
    sensitive << ( tmp_reg_706 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_buffer_val_0_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_6_fu_267_p1 );

    SC_METHOD(thread_buffer_val_0_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_buffer_val_0_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_buffer_val_0_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_4_reg_730 );
    sensitive << ( tmp_reg_706 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_buffer_val_1_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_6_fu_267_p1 );

    SC_METHOD(thread_buffer_val_1_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_buffer_val_1_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_buffer_val_1_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_4_reg_730 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exitcond3_fu_209_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_187 );

    SC_METHOD(thread_exitcond_fu_249_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( col_assign_reg_198 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_599_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_grp_fu_599_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( grp_fu_599_p10 );

    SC_METHOD(thread_grp_fu_599_p10);
    sensitive << ( okno_val_0_0_fu_372_p3 );

    SC_METHOD(thread_grp_fu_599_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( p_shl1_fu_395_p1 );
    sensitive << ( rhs_V_0_1_i_cast_fu_383_p1 );

    SC_METHOD(thread_grp_fu_607_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_grp_fu_607_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( grp_fu_607_p10 );

    SC_METHOD(thread_grp_fu_607_p10);
    sensitive << ( okno_val_0_1_s_fu_108 );

    SC_METHOD(thread_grp_fu_607_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( p_shl2_fu_421_p1 );
    sensitive << ( rhs_V_1_i_cast_fu_409_p1 );

    SC_METHOD(thread_grp_fu_615_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_grp_fu_615_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( grp_fu_615_p10 );

    SC_METHOD(thread_grp_fu_615_p10);
    sensitive << ( okno_val_1_0_s_fu_112 );

    SC_METHOD(thread_grp_fu_615_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( grp_fu_615_p20 );

    SC_METHOD(thread_grp_fu_615_p20);
    sensitive << ( ret_V_1_2_i_fu_451_p2 );

    SC_METHOD(thread_grp_fu_623_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_grp_fu_623_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( grp_fu_623_p10 );

    SC_METHOD(thread_grp_fu_623_p10);
    sensitive << ( okno_val_2_0_fu_358_p3 );

    SC_METHOD(thread_grp_fu_623_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( grp_fu_623_p20 );

    SC_METHOD(thread_grp_fu_623_p20);
    sensitive << ( grp_fu_631_p3 );

    SC_METHOD(thread_grp_fu_631_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_grp_fu_631_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( grp_fu_631_p10 );

    SC_METHOD(thread_grp_fu_631_p10);
    sensitive << ( okno_val_2_1_s_fu_128 );

    SC_METHOD(thread_grp_fu_631_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( p_shl_fu_477_p1 );
    sensitive << ( rhs_V_2_1_i_cast_fu_465_p1 );

    SC_METHOD(thread_i_1_fu_215_p2);
    sensitive << ( i_reg_187 );

    SC_METHOD(thread_icmp1_fu_283_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond_fu_249_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_13_fu_273_p4 );

    SC_METHOD(thread_icmp_fu_237_p2);
    sensitive << ( exitcond3_fu_209_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_fu_227_p4 );

    SC_METHOD(thread_img_in_data_stream_V_blk_n);
    sensitive << ( img_in_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_4_reg_730 );
    sensitive << ( tmp_reg_706 );

    SC_METHOD(thread_img_in_data_stream_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_predicate_op64_read_state4 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_img_out_data_stream_V_blk_n);
    sensitive << ( img_out_data_stream_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( or_cond6_reg_755_pp0_iter3_reg );

    SC_METHOD(thread_img_out_data_stream_V_din);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( or_cond6_reg_755_pp0_iter3_reg );
    sensitive << ( tmp_12_reg_779 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_img_out_data_stream_V_write);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( or_cond6_reg_755_pp0_iter3_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( exitcond3_fu_209_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_j_fu_255_p2);
    sensitive << ( col_assign_reg_198 );

    SC_METHOD(thread_okno_val_0_0_fu_372_p3);
    sensitive << ( tmp_4_reg_730_pp0_iter1_reg );
    sensitive << ( okno_val_0_0_s_fu_104 );
    sensitive << ( okno_val_0_0_1_fu_120 );

    SC_METHOD(thread_okno_val_1_0_1_fu_354_p1);
    sensitive << ( tmp1_1_fu_100 );

    SC_METHOD(thread_okno_val_1_0_fu_365_p3);
    sensitive << ( tmp_4_reg_730_pp0_iter1_reg );
    sensitive << ( okno_val_1_0_s_fu_112 );
    sensitive << ( okno_val_1_0_1_fu_354_p1 );

    SC_METHOD(thread_okno_val_2_0_1_fu_350_p1);
    sensitive << ( tmp2_1_fu_96 );

    SC_METHOD(thread_okno_val_2_0_fu_358_p3);
    sensitive << ( tmp_4_reg_730_pp0_iter1_reg );
    sensitive << ( okno_val_2_0_s_fu_124 );
    sensitive << ( okno_val_2_0_1_fu_350_p1 );

    SC_METHOD(thread_or_cond5_fu_541_p2);
    sensitive << ( tmp4_fu_537_p2 );
    sensitive << ( tmp3_fu_533_p2 );

    SC_METHOD(thread_or_cond6_fu_295_p2);
    sensitive << ( tmp_2_reg_716 );
    sensitive << ( tmp_s_fu_289_p2 );

    SC_METHOD(thread_p_shl1_fu_395_p1);
    sensitive << ( tmp_14_fu_387_p3 );

    SC_METHOD(thread_p_shl2_fu_421_p1);
    sensitive << ( tmp_15_fu_413_p3 );

    SC_METHOD(thread_p_shl3_fu_447_p1);
    sensitive << ( tmp_16_fu_439_p3 );

    SC_METHOD(thread_p_shl_fu_477_p1);
    sensitive << ( tmp_17_fu_469_p3 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_ret_V_1_2_i_fu_451_p2);
    sensitive << ( p_shl3_fu_447_p1 );
    sensitive << ( rhs_V_1_2_i_cast_fu_435_p1 );

    SC_METHOD(thread_rhs_V_0_1_i_cast_fu_383_p1);
    sensitive << ( okno_val_0_0_s_fu_104 );

    SC_METHOD(thread_rhs_V_1_2_i_cast_fu_435_p1);
    sensitive << ( okno_val_1_1_s_fu_116 );

    SC_METHOD(thread_rhs_V_1_i_cast_fu_409_p1);
    sensitive << ( okno_val_1_0_fu_365_p3 );

    SC_METHOD(thread_rhs_V_2_1_i_cast_fu_465_p1);
    sensitive << ( okno_val_2_0_s_fu_124 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp10_cast_fu_566_p1);
    sensitive << ( tmp10_reg_774 );

    SC_METHOD(thread_tmp1_fu_300_p1);
    sensitive << ( buffer_val_0_q0 );

    SC_METHOD(thread_tmp2_fu_304_p1);
    sensitive << ( buffer_val_1_q0 );

    SC_METHOD(thread_tmp3_fu_533_p2);
    sensitive << ( icmp_reg_711 );
    sensitive << ( icmp1_reg_750_pp0_iter2_reg );

    SC_METHOD(thread_tmp4_fu_537_p2);
    sensitive << ( tmp_reg_706 );
    sensitive << ( tmp_4_reg_730_pp0_iter2_reg );

    SC_METHOD(thread_tmp5_cast_fu_559_p1);
    sensitive << ( tmp5_fu_553_p2 );

    SC_METHOD(thread_tmp5_fu_553_p2);
    sensitive << ( tmp6_cast_fu_547_p1 );
    sensitive << ( tmp7_cast_fu_550_p1 );

    SC_METHOD(thread_tmp6_cast_fu_547_p1);
    sensitive << ( tmp6_reg_759 );

    SC_METHOD(thread_tmp7_cast_fu_550_p1);
    sensitive << ( tmp7_reg_764 );

    SC_METHOD(thread_tmp8_fu_569_p2);
    sensitive << ( tmp9_cast_fu_563_p1 );
    sensitive << ( tmp10_cast_fu_566_p1 );

    SC_METHOD(thread_tmp9_cast_fu_563_p1);
    sensitive << ( tmp9_reg_769 );

    SC_METHOD(thread_tmp_12_fu_591_p3);
    sensitive << ( or_cond5_fu_541_p2 );
    sensitive << ( v0_assign_fu_581_p4 );

    SC_METHOD(thread_tmp_13_fu_273_p4);
    sensitive << ( col_assign_reg_198 );

    SC_METHOD(thread_tmp_14_fu_387_p3);
    sensitive << ( okno_val_0_0_s_fu_104 );

    SC_METHOD(thread_tmp_15_fu_413_p3);
    sensitive << ( okno_val_1_0_fu_365_p3 );

    SC_METHOD(thread_tmp_16_fu_439_p3);
    sensitive << ( okno_val_1_1_s_fu_116 );

    SC_METHOD(thread_tmp_17_fu_469_p3);
    sensitive << ( okno_val_2_0_s_fu_124 );

    SC_METHOD(thread_tmp_1_fu_227_p4);
    sensitive << ( i_reg_187 );

    SC_METHOD(thread_tmp_2_fu_243_p2);
    sensitive << ( exitcond3_fu_209_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_187 );

    SC_METHOD(thread_tmp_4_fu_261_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( col_assign_reg_198 );
    sensitive << ( exitcond_fu_249_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_6_fu_267_p1);
    sensitive << ( col_assign_reg_198 );

    SC_METHOD(thread_tmp_fu_221_p2);
    sensitive << ( exitcond3_fu_209_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_187 );

    SC_METHOD(thread_tmp_s_fu_289_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( col_assign_reg_198 );
    sensitive << ( exitcond_fu_249_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_v0_assign_fu_581_p4);
    sensitive << ( acc_V_2_2_i_fu_575_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond3_fu_209_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_249_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "rozmycie_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, img_in_data_stream_V_dout, "(port)img_in_data_stream_V_dout");
    sc_trace(mVcdFile, img_in_data_stream_V_empty_n, "(port)img_in_data_stream_V_empty_n");
    sc_trace(mVcdFile, img_in_data_stream_V_read, "(port)img_in_data_stream_V_read");
    sc_trace(mVcdFile, img_out_data_stream_V_din, "(port)img_out_data_stream_V_din");
    sc_trace(mVcdFile, img_out_data_stream_V_full_n, "(port)img_out_data_stream_V_full_n");
    sc_trace(mVcdFile, img_out_data_stream_V_write, "(port)img_out_data_stream_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, img_in_data_stream_V_blk_n, "img_in_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_4_reg_730, "tmp_4_reg_730");
    sc_trace(mVcdFile, tmp_reg_706, "tmp_reg_706");
    sc_trace(mVcdFile, img_out_data_stream_V_blk_n, "img_out_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, or_cond6_reg_755, "or_cond6_reg_755");
    sc_trace(mVcdFile, or_cond6_reg_755_pp0_iter3_reg, "or_cond6_reg_755_pp0_iter3_reg");
    sc_trace(mVcdFile, col_assign_reg_198, "col_assign_reg_198");
    sc_trace(mVcdFile, exitcond3_fu_209_p2, "exitcond3_fu_209_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_1_fu_215_p2, "i_1_fu_215_p2");
    sc_trace(mVcdFile, i_1_reg_701, "i_1_reg_701");
    sc_trace(mVcdFile, tmp_fu_221_p2, "tmp_fu_221_p2");
    sc_trace(mVcdFile, icmp_fu_237_p2, "icmp_fu_237_p2");
    sc_trace(mVcdFile, icmp_reg_711, "icmp_reg_711");
    sc_trace(mVcdFile, tmp_2_fu_243_p2, "tmp_2_fu_243_p2");
    sc_trace(mVcdFile, tmp_2_reg_716, "tmp_2_reg_716");
    sc_trace(mVcdFile, exitcond_fu_249_p2, "exitcond_fu_249_p2");
    sc_trace(mVcdFile, exitcond_reg_721, "exitcond_reg_721");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_predicate_op64_read_state4, "ap_predicate_op64_read_state4");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter3, "ap_block_state6_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter4, "ap_block_state7_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond_reg_721_pp0_iter1_reg, "exitcond_reg_721_pp0_iter1_reg");
    sc_trace(mVcdFile, j_fu_255_p2, "j_fu_255_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_4_fu_261_p2, "tmp_4_fu_261_p2");
    sc_trace(mVcdFile, tmp_4_reg_730_pp0_iter1_reg, "tmp_4_reg_730_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_4_reg_730_pp0_iter2_reg, "tmp_4_reg_730_pp0_iter2_reg");
    sc_trace(mVcdFile, buffer_val_1_addr_reg_738, "buffer_val_1_addr_reg_738");
    sc_trace(mVcdFile, buffer_val_0_addr_reg_744, "buffer_val_0_addr_reg_744");
    sc_trace(mVcdFile, icmp1_fu_283_p2, "icmp1_fu_283_p2");
    sc_trace(mVcdFile, icmp1_reg_750, "icmp1_reg_750");
    sc_trace(mVcdFile, icmp1_reg_750_pp0_iter1_reg, "icmp1_reg_750_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp1_reg_750_pp0_iter2_reg, "icmp1_reg_750_pp0_iter2_reg");
    sc_trace(mVcdFile, or_cond6_fu_295_p2, "or_cond6_fu_295_p2");
    sc_trace(mVcdFile, or_cond6_reg_755_pp0_iter1_reg, "or_cond6_reg_755_pp0_iter1_reg");
    sc_trace(mVcdFile, or_cond6_reg_755_pp0_iter2_reg, "or_cond6_reg_755_pp0_iter2_reg");
    sc_trace(mVcdFile, grp_fu_599_p3, "grp_fu_599_p3");
    sc_trace(mVcdFile, tmp6_reg_759, "tmp6_reg_759");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, grp_fu_607_p3, "grp_fu_607_p3");
    sc_trace(mVcdFile, tmp7_reg_764, "tmp7_reg_764");
    sc_trace(mVcdFile, grp_fu_615_p3, "grp_fu_615_p3");
    sc_trace(mVcdFile, tmp9_reg_769, "tmp9_reg_769");
    sc_trace(mVcdFile, grp_fu_623_p3, "grp_fu_623_p3");
    sc_trace(mVcdFile, tmp10_reg_774, "tmp10_reg_774");
    sc_trace(mVcdFile, tmp_12_fu_591_p3, "tmp_12_fu_591_p3");
    sc_trace(mVcdFile, tmp_12_reg_779, "tmp_12_reg_779");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, buffer_val_0_address0, "buffer_val_0_address0");
    sc_trace(mVcdFile, buffer_val_0_ce0, "buffer_val_0_ce0");
    sc_trace(mVcdFile, buffer_val_0_q0, "buffer_val_0_q0");
    sc_trace(mVcdFile, buffer_val_0_ce1, "buffer_val_0_ce1");
    sc_trace(mVcdFile, buffer_val_0_we1, "buffer_val_0_we1");
    sc_trace(mVcdFile, buffer_val_1_address0, "buffer_val_1_address0");
    sc_trace(mVcdFile, buffer_val_1_ce0, "buffer_val_1_ce0");
    sc_trace(mVcdFile, buffer_val_1_q0, "buffer_val_1_q0");
    sc_trace(mVcdFile, buffer_val_1_ce1, "buffer_val_1_ce1");
    sc_trace(mVcdFile, buffer_val_1_we1, "buffer_val_1_we1");
    sc_trace(mVcdFile, i_reg_187, "i_reg_187");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_6_fu_267_p1, "tmp_6_fu_267_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, tmp2_1_fu_96, "tmp2_1_fu_96");
    sc_trace(mVcdFile, tmp2_fu_304_p1, "tmp2_fu_304_p1");
    sc_trace(mVcdFile, tmp1_1_fu_100, "tmp1_1_fu_100");
    sc_trace(mVcdFile, tmp1_fu_300_p1, "tmp1_fu_300_p1");
    sc_trace(mVcdFile, okno_val_0_0_s_fu_104, "okno_val_0_0_s_fu_104");
    sc_trace(mVcdFile, okno_val_0_0_fu_372_p3, "okno_val_0_0_fu_372_p3");
    sc_trace(mVcdFile, okno_val_0_1_s_fu_108, "okno_val_0_1_s_fu_108");
    sc_trace(mVcdFile, okno_val_1_0_s_fu_112, "okno_val_1_0_s_fu_112");
    sc_trace(mVcdFile, okno_val_1_0_fu_365_p3, "okno_val_1_0_fu_365_p3");
    sc_trace(mVcdFile, okno_val_1_1_s_fu_116, "okno_val_1_1_s_fu_116");
    sc_trace(mVcdFile, okno_val_0_0_1_fu_120, "okno_val_0_0_1_fu_120");
    sc_trace(mVcdFile, okno_val_2_0_s_fu_124, "okno_val_2_0_s_fu_124");
    sc_trace(mVcdFile, okno_val_2_0_fu_358_p3, "okno_val_2_0_fu_358_p3");
    sc_trace(mVcdFile, okno_val_2_1_s_fu_128, "okno_val_2_1_s_fu_128");
    sc_trace(mVcdFile, tmp_1_fu_227_p4, "tmp_1_fu_227_p4");
    sc_trace(mVcdFile, tmp_13_fu_273_p4, "tmp_13_fu_273_p4");
    sc_trace(mVcdFile, tmp_s_fu_289_p2, "tmp_s_fu_289_p2");
    sc_trace(mVcdFile, okno_val_2_0_1_fu_350_p1, "okno_val_2_0_1_fu_350_p1");
    sc_trace(mVcdFile, okno_val_1_0_1_fu_354_p1, "okno_val_1_0_1_fu_354_p1");
    sc_trace(mVcdFile, tmp_14_fu_387_p3, "tmp_14_fu_387_p3");
    sc_trace(mVcdFile, p_shl1_fu_395_p1, "p_shl1_fu_395_p1");
    sc_trace(mVcdFile, rhs_V_0_1_i_cast_fu_383_p1, "rhs_V_0_1_i_cast_fu_383_p1");
    sc_trace(mVcdFile, tmp_15_fu_413_p3, "tmp_15_fu_413_p3");
    sc_trace(mVcdFile, p_shl2_fu_421_p1, "p_shl2_fu_421_p1");
    sc_trace(mVcdFile, rhs_V_1_i_cast_fu_409_p1, "rhs_V_1_i_cast_fu_409_p1");
    sc_trace(mVcdFile, tmp_16_fu_439_p3, "tmp_16_fu_439_p3");
    sc_trace(mVcdFile, p_shl3_fu_447_p1, "p_shl3_fu_447_p1");
    sc_trace(mVcdFile, rhs_V_1_2_i_cast_fu_435_p1, "rhs_V_1_2_i_cast_fu_435_p1");
    sc_trace(mVcdFile, ret_V_1_2_i_fu_451_p2, "ret_V_1_2_i_fu_451_p2");
    sc_trace(mVcdFile, tmp_17_fu_469_p3, "tmp_17_fu_469_p3");
    sc_trace(mVcdFile, p_shl_fu_477_p1, "p_shl_fu_477_p1");
    sc_trace(mVcdFile, rhs_V_2_1_i_cast_fu_465_p1, "rhs_V_2_1_i_cast_fu_465_p1");
    sc_trace(mVcdFile, grp_fu_631_p3, "grp_fu_631_p3");
    sc_trace(mVcdFile, tmp4_fu_537_p2, "tmp4_fu_537_p2");
    sc_trace(mVcdFile, tmp3_fu_533_p2, "tmp3_fu_533_p2");
    sc_trace(mVcdFile, tmp6_cast_fu_547_p1, "tmp6_cast_fu_547_p1");
    sc_trace(mVcdFile, tmp7_cast_fu_550_p1, "tmp7_cast_fu_550_p1");
    sc_trace(mVcdFile, tmp5_fu_553_p2, "tmp5_fu_553_p2");
    sc_trace(mVcdFile, tmp9_cast_fu_563_p1, "tmp9_cast_fu_563_p1");
    sc_trace(mVcdFile, tmp10_cast_fu_566_p1, "tmp10_cast_fu_566_p1");
    sc_trace(mVcdFile, tmp5_cast_fu_559_p1, "tmp5_cast_fu_559_p1");
    sc_trace(mVcdFile, tmp8_fu_569_p2, "tmp8_fu_569_p2");
    sc_trace(mVcdFile, acc_V_2_2_i_fu_575_p2, "acc_V_2_2_i_fu_575_p2");
    sc_trace(mVcdFile, or_cond5_fu_541_p2, "or_cond5_fu_541_p2");
    sc_trace(mVcdFile, v0_assign_fu_581_p4, "v0_assign_fu_581_p4");
    sc_trace(mVcdFile, grp_fu_599_p0, "grp_fu_599_p0");
    sc_trace(mVcdFile, grp_fu_599_p1, "grp_fu_599_p1");
    sc_trace(mVcdFile, grp_fu_599_p2, "grp_fu_599_p2");
    sc_trace(mVcdFile, grp_fu_607_p0, "grp_fu_607_p0");
    sc_trace(mVcdFile, grp_fu_607_p1, "grp_fu_607_p1");
    sc_trace(mVcdFile, grp_fu_607_p2, "grp_fu_607_p2");
    sc_trace(mVcdFile, grp_fu_615_p0, "grp_fu_615_p0");
    sc_trace(mVcdFile, grp_fu_615_p1, "grp_fu_615_p1");
    sc_trace(mVcdFile, grp_fu_615_p2, "grp_fu_615_p2");
    sc_trace(mVcdFile, grp_fu_623_p0, "grp_fu_623_p0");
    sc_trace(mVcdFile, grp_fu_623_p1, "grp_fu_623_p1");
    sc_trace(mVcdFile, grp_fu_623_p2, "grp_fu_623_p2");
    sc_trace(mVcdFile, grp_fu_631_p0, "grp_fu_631_p0");
    sc_trace(mVcdFile, grp_fu_631_p1, "grp_fu_631_p1");
    sc_trace(mVcdFile, grp_fu_631_p2, "grp_fu_631_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, grp_fu_599_p10, "grp_fu_599_p10");
    sc_trace(mVcdFile, grp_fu_607_p10, "grp_fu_607_p10");
    sc_trace(mVcdFile, grp_fu_615_p10, "grp_fu_615_p10");
    sc_trace(mVcdFile, grp_fu_615_p20, "grp_fu_615_p20");
    sc_trace(mVcdFile, grp_fu_623_p10, "grp_fu_623_p10");
    sc_trace(mVcdFile, grp_fu_623_p20, "grp_fu_623_p20");
    sc_trace(mVcdFile, grp_fu_631_p10, "grp_fu_631_p10");
#endif

    }
}

rozmycie::~rozmycie() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete buffer_val_0_U;
    delete buffer_val_1_U;
    delete filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U9;
    delete filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U10;
    delete filtr_Gauss_mac_muladd_7ns_8ns_14ns_15_1_1_U11;
    delete filtr_Gauss_mac_muladd_6ns_8ns_14ns_15_1_1_U12;
    delete filtr_Gauss_mac_muladd_6ns_8ns_14ns_14_1_1_U13;
}

void rozmycie::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_209_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(exitcond3_fu_209_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(exitcond3_fu_209_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter4 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_249_p2.read()))) {
        col_assign_reg_198 = j_fu_255_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond3_fu_209_p2.read(), ap_const_lv1_0))) {
        col_assign_reg_198 = ap_const_lv11_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_reg_187 = i_1_reg_701.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_reg_187 = ap_const_lv10_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_249_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_fu_261_p2.read()))) {
        buffer_val_0_addr_reg_744 =  (sc_lv<11>) (tmp_6_fu_267_p1.read());
        buffer_val_1_addr_reg_738 =  (sc_lv<11>) (tmp_6_fu_267_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_reg_721 = exitcond_fu_249_p2.read();
        exitcond_reg_721_pp0_iter1_reg = exitcond_reg_721.read();
        icmp1_reg_750_pp0_iter1_reg = icmp1_reg_750.read();
        or_cond6_reg_755_pp0_iter1_reg = or_cond6_reg_755.read();
        tmp_4_reg_730_pp0_iter1_reg = tmp_4_reg_730.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_1_reg_701 = i_1_fu_215_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_249_p2.read()))) {
        icmp1_reg_750 = icmp1_fu_283_p2.read();
        or_cond6_reg_755 = or_cond6_fu_295_p2.read();
        tmp_4_reg_730 = tmp_4_fu_261_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        icmp1_reg_750_pp0_iter2_reg = icmp1_reg_750_pp0_iter1_reg.read();
        or_cond6_reg_755_pp0_iter2_reg = or_cond6_reg_755_pp0_iter1_reg.read();
        or_cond6_reg_755_pp0_iter3_reg = or_cond6_reg_755_pp0_iter2_reg.read();
        tmp_12_reg_779 = tmp_12_fu_591_p3.read();
        tmp_4_reg_730_pp0_iter2_reg = tmp_4_reg_730_pp0_iter1_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond3_fu_209_p2.read(), ap_const_lv1_0))) {
        icmp_reg_711 = icmp_fu_237_p2.read();
        tmp_2_reg_716 = tmp_2_fu_243_p2.read();
        tmp_reg_706 = tmp_fu_221_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(tmp_4_reg_730.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_706.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        okno_val_0_0_1_fu_120 = img_in_data_stream_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_721_pp0_iter1_reg.read()))) {
        okno_val_0_0_s_fu_104 = okno_val_0_0_fu_372_p3.read();
        okno_val_0_1_s_fu_108 = okno_val_0_0_s_fu_104.read();
        okno_val_1_0_s_fu_112 = okno_val_1_0_fu_365_p3.read();
        okno_val_1_1_s_fu_116 = okno_val_1_0_s_fu_112.read();
        okno_val_2_0_s_fu_124 = okno_val_2_0_fu_358_p3.read();
        okno_val_2_1_s_fu_128 = okno_val_2_0_s_fu_124.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        tmp10_reg_774 = grp_fu_623_p3.read();
        tmp6_reg_759 = grp_fu_599_p3.read();
        tmp7_reg_764 = grp_fu_607_p3.read();
        tmp9_reg_769 = grp_fu_615_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(tmp_4_reg_730.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp1_1_fu_100 = tmp1_fu_300_p1.read();
        tmp2_1_fu_96 = tmp2_fu_304_p1.read();
    }
}

void rozmycie::thread_acc_V_2_2_i_fu_575_p2() {
    acc_V_2_2_i_fu_575_p2 = (!tmp5_cast_fu_559_p1.read().is_01() || !tmp8_fu_569_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp5_cast_fu_559_p1.read()) + sc_biguint<16>(tmp8_fu_569_p2.read()));
}

void rozmycie::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void rozmycie::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void rozmycie::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void rozmycie::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[3];
}

void rozmycie::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void rozmycie::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op64_read_state4.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, or_cond6_reg_755_pp0_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_out_data_stream_V_full_n.read())));
}

void rozmycie::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op64_read_state4.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, or_cond6_reg_755_pp0_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_out_data_stream_V_full_n.read())));
}

void rozmycie::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op64_read_state4.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, or_cond6_reg_755_pp0_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_out_data_stream_V_full_n.read())));
}

void rozmycie::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void rozmycie::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void rozmycie::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_V_empty_n.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op64_read_state4.read()));
}

void rozmycie::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void rozmycie::thread_ap_block_state6_pp0_stage0_iter3() {
    ap_block_state6_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void rozmycie::thread_ap_block_state7_pp0_stage0_iter4() {
    ap_block_state7_pp0_stage0_iter4 = (esl_seteq<1,1,1>(ap_const_lv1_1, or_cond6_reg_755_pp0_iter3_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, img_out_data_stream_V_full_n.read()));
}

void rozmycie::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_249_p2.read())) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void rozmycie::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_209_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void rozmycie::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void rozmycie::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void rozmycie::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void rozmycie::thread_ap_predicate_op64_read_state4() {
    ap_predicate_op64_read_state4 = (esl_seteq<1,1,1>(tmp_4_reg_730.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_706.read()));
}

void rozmycie::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void rozmycie::thread_buffer_val_0_address0() {
    buffer_val_0_address0 =  (sc_lv<11>) (tmp_6_fu_267_p1.read());
}

void rozmycie::thread_buffer_val_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        buffer_val_0_ce0 = ap_const_logic_1;
    } else {
        buffer_val_0_ce0 = ap_const_logic_0;
    }
}

void rozmycie::thread_buffer_val_0_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        buffer_val_0_ce1 = ap_const_logic_1;
    } else {
        buffer_val_0_ce1 = ap_const_logic_0;
    }
}

void rozmycie::thread_buffer_val_0_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_4_reg_730.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_706.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        buffer_val_0_we1 = ap_const_logic_1;
    } else {
        buffer_val_0_we1 = ap_const_logic_0;
    }
}

void rozmycie::thread_buffer_val_1_address0() {
    buffer_val_1_address0 =  (sc_lv<11>) (tmp_6_fu_267_p1.read());
}

void rozmycie::thread_buffer_val_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        buffer_val_1_ce0 = ap_const_logic_1;
    } else {
        buffer_val_1_ce0 = ap_const_logic_0;
    }
}

void rozmycie::thread_buffer_val_1_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        buffer_val_1_ce1 = ap_const_logic_1;
    } else {
        buffer_val_1_ce1 = ap_const_logic_0;
    }
}

void rozmycie::thread_buffer_val_1_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_4_reg_730.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        buffer_val_1_we1 = ap_const_logic_1;
    } else {
        buffer_val_1_we1 = ap_const_logic_0;
    }
}

void rozmycie::thread_exitcond3_fu_209_p2() {
    exitcond3_fu_209_p2 = (!i_reg_187.read().is_01() || !ap_const_lv10_2D1.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_187.read() == ap_const_lv10_2D1);
}

void rozmycie::thread_exitcond_fu_249_p2() {
    exitcond_fu_249_p2 = (!col_assign_reg_198.read().is_01() || !ap_const_lv11_501.is_01())? sc_lv<1>(): sc_lv<1>(col_assign_reg_198.read() == ap_const_lv11_501);
}

void rozmycie::thread_grp_fu_599_p0() {
    grp_fu_599_p0 =  (sc_lv<6>) (ap_const_lv14_13);
}

void rozmycie::thread_grp_fu_599_p1() {
    grp_fu_599_p1 =  (sc_lv<8>) (grp_fu_599_p10.read());
}

void rozmycie::thread_grp_fu_599_p10() {
    grp_fu_599_p10 = esl_zext<14,8>(okno_val_0_0_fu_372_p3.read());
}

void rozmycie::thread_grp_fu_599_p2() {
    grp_fu_599_p2 = (!p_shl1_fu_395_p1.read().is_01() || !rhs_V_0_1_i_cast_fu_383_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(p_shl1_fu_395_p1.read()) - sc_biguint<14>(rhs_V_0_1_i_cast_fu_383_p1.read()));
}

void rozmycie::thread_grp_fu_607_p0() {
    grp_fu_607_p0 =  (sc_lv<6>) (ap_const_lv14_13);
}

void rozmycie::thread_grp_fu_607_p1() {
    grp_fu_607_p1 =  (sc_lv<8>) (grp_fu_607_p10.read());
}

void rozmycie::thread_grp_fu_607_p10() {
    grp_fu_607_p10 = esl_zext<14,8>(okno_val_0_1_s_fu_108.read());
}

void rozmycie::thread_grp_fu_607_p2() {
    grp_fu_607_p2 = (!p_shl2_fu_421_p1.read().is_01() || !rhs_V_1_i_cast_fu_409_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(p_shl2_fu_421_p1.read()) - sc_biguint<14>(rhs_V_1_i_cast_fu_409_p1.read()));
}

void rozmycie::thread_grp_fu_615_p0() {
    grp_fu_615_p0 =  (sc_lv<7>) (ap_const_lv15_34);
}

void rozmycie::thread_grp_fu_615_p1() {
    grp_fu_615_p1 =  (sc_lv<8>) (grp_fu_615_p10.read());
}

void rozmycie::thread_grp_fu_615_p10() {
    grp_fu_615_p10 = esl_zext<15,8>(okno_val_1_0_s_fu_112.read());
}

void rozmycie::thread_grp_fu_615_p2() {
    grp_fu_615_p2 =  (sc_lv<14>) (grp_fu_615_p20.read());
}

void rozmycie::thread_grp_fu_615_p20() {
    grp_fu_615_p20 = esl_zext<15,14>(ret_V_1_2_i_fu_451_p2.read());
}

void rozmycie::thread_grp_fu_623_p0() {
    grp_fu_623_p0 =  (sc_lv<6>) (ap_const_lv14_13);
}

void rozmycie::thread_grp_fu_623_p1() {
    grp_fu_623_p1 =  (sc_lv<8>) (grp_fu_623_p10.read());
}

void rozmycie::thread_grp_fu_623_p10() {
    grp_fu_623_p10 = esl_zext<14,8>(okno_val_2_0_fu_358_p3.read());
}

void rozmycie::thread_grp_fu_623_p2() {
    grp_fu_623_p2 =  (sc_lv<14>) (grp_fu_623_p20.read());
}

void rozmycie::thread_grp_fu_623_p20() {
    grp_fu_623_p20 = esl_zext<15,14>(grp_fu_631_p3.read());
}

void rozmycie::thread_grp_fu_631_p0() {
    grp_fu_631_p0 =  (sc_lv<6>) (ap_const_lv14_13);
}

void rozmycie::thread_grp_fu_631_p1() {
    grp_fu_631_p1 =  (sc_lv<8>) (grp_fu_631_p10.read());
}

void rozmycie::thread_grp_fu_631_p10() {
    grp_fu_631_p10 = esl_zext<14,8>(okno_val_2_1_s_fu_128.read());
}

void rozmycie::thread_grp_fu_631_p2() {
    grp_fu_631_p2 = (!p_shl_fu_477_p1.read().is_01() || !rhs_V_2_1_i_cast_fu_465_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(p_shl_fu_477_p1.read()) - sc_biguint<14>(rhs_V_2_1_i_cast_fu_465_p1.read()));
}

void rozmycie::thread_i_1_fu_215_p2() {
    i_1_fu_215_p2 = (!i_reg_187.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(i_reg_187.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void rozmycie::thread_icmp1_fu_283_p2() {
    icmp1_fu_283_p2 = (!tmp_13_fu_273_p4.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_13_fu_273_p4.read() != ap_const_lv10_0);
}

void rozmycie::thread_icmp_fu_237_p2() {
    icmp_fu_237_p2 = (!tmp_1_fu_227_p4.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_1_fu_227_p4.read() != ap_const_lv9_0);
}

void rozmycie::thread_img_in_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(tmp_4_reg_730.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_reg_706.read()))) {
        img_in_data_stream_V_blk_n = img_in_data_stream_V_empty_n.read();
    } else {
        img_in_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void rozmycie::thread_img_in_data_stream_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op64_read_state4.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        img_in_data_stream_V_read = ap_const_logic_1;
    } else {
        img_in_data_stream_V_read = ap_const_logic_0;
    }
}

void rozmycie::thread_img_out_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_cond6_reg_755_pp0_iter3_reg.read()))) {
        img_out_data_stream_V_blk_n = img_out_data_stream_V_full_n.read();
    } else {
        img_out_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void rozmycie::thread_img_out_data_stream_V_din() {
    img_out_data_stream_V_din = tmp_12_reg_779.read();
}

void rozmycie::thread_img_out_data_stream_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_cond6_reg_755_pp0_iter3_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        img_out_data_stream_V_write = ap_const_logic_1;
    } else {
        img_out_data_stream_V_write = ap_const_logic_0;
    }
}

void rozmycie::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_209_p2.read()))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void rozmycie::thread_j_fu_255_p2() {
    j_fu_255_p2 = (!col_assign_reg_198.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(col_assign_reg_198.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void rozmycie::thread_okno_val_0_0_fu_372_p3() {
    okno_val_0_0_fu_372_p3 = (!tmp_4_reg_730_pp0_iter1_reg.read()[0].is_01())? sc_lv<8>(): ((tmp_4_reg_730_pp0_iter1_reg.read()[0].to_bool())? okno_val_0_0_1_fu_120.read(): okno_val_0_0_s_fu_104.read());
}

void rozmycie::thread_okno_val_1_0_1_fu_354_p1() {
    okno_val_1_0_1_fu_354_p1 = tmp1_1_fu_100.read().range(8-1, 0);
}

void rozmycie::thread_okno_val_1_0_fu_365_p3() {
    okno_val_1_0_fu_365_p3 = (!tmp_4_reg_730_pp0_iter1_reg.read()[0].is_01())? sc_lv<8>(): ((tmp_4_reg_730_pp0_iter1_reg.read()[0].to_bool())? okno_val_1_0_1_fu_354_p1.read(): okno_val_1_0_s_fu_112.read());
}

void rozmycie::thread_okno_val_2_0_1_fu_350_p1() {
    okno_val_2_0_1_fu_350_p1 = tmp2_1_fu_96.read().range(8-1, 0);
}

void rozmycie::thread_okno_val_2_0_fu_358_p3() {
    okno_val_2_0_fu_358_p3 = (!tmp_4_reg_730_pp0_iter1_reg.read()[0].is_01())? sc_lv<8>(): ((tmp_4_reg_730_pp0_iter1_reg.read()[0].to_bool())? okno_val_2_0_1_fu_350_p1.read(): okno_val_2_0_s_fu_124.read());
}

void rozmycie::thread_or_cond5_fu_541_p2() {
    or_cond5_fu_541_p2 = (tmp4_fu_537_p2.read() & tmp3_fu_533_p2.read());
}

void rozmycie::thread_or_cond6_fu_295_p2() {
    or_cond6_fu_295_p2 = (tmp_2_reg_716.read() & tmp_s_fu_289_p2.read());
}

void rozmycie::thread_p_shl1_fu_395_p1() {
    p_shl1_fu_395_p1 = esl_zext<14,13>(tmp_14_fu_387_p3.read());
}

void rozmycie::thread_p_shl2_fu_421_p1() {
    p_shl2_fu_421_p1 = esl_zext<14,13>(tmp_15_fu_413_p3.read());
}

void rozmycie::thread_p_shl3_fu_447_p1() {
    p_shl3_fu_447_p1 = esl_zext<14,13>(tmp_16_fu_439_p3.read());
}

void rozmycie::thread_p_shl_fu_477_p1() {
    p_shl_fu_477_p1 = esl_zext<14,13>(tmp_17_fu_469_p3.read());
}

void rozmycie::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void rozmycie::thread_ret_V_1_2_i_fu_451_p2() {
    ret_V_1_2_i_fu_451_p2 = (!p_shl3_fu_447_p1.read().is_01() || !rhs_V_1_2_i_cast_fu_435_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(p_shl3_fu_447_p1.read()) - sc_biguint<14>(rhs_V_1_2_i_cast_fu_435_p1.read()));
}

void rozmycie::thread_rhs_V_0_1_i_cast_fu_383_p1() {
    rhs_V_0_1_i_cast_fu_383_p1 = esl_zext<14,8>(okno_val_0_0_s_fu_104.read());
}

void rozmycie::thread_rhs_V_1_2_i_cast_fu_435_p1() {
    rhs_V_1_2_i_cast_fu_435_p1 = esl_zext<14,8>(okno_val_1_1_s_fu_116.read());
}

void rozmycie::thread_rhs_V_1_i_cast_fu_409_p1() {
    rhs_V_1_i_cast_fu_409_p1 = esl_zext<14,8>(okno_val_1_0_fu_365_p3.read());
}

void rozmycie::thread_rhs_V_2_1_i_cast_fu_465_p1() {
    rhs_V_2_1_i_cast_fu_465_p1 = esl_zext<14,8>(okno_val_2_0_s_fu_124.read());
}

void rozmycie::thread_start_out() {
    start_out = real_start.read();
}

void rozmycie::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void rozmycie::thread_tmp10_cast_fu_566_p1() {
    tmp10_cast_fu_566_p1 = esl_zext<16,15>(tmp10_reg_774.read());
}

void rozmycie::thread_tmp1_fu_300_p1() {
    tmp1_fu_300_p1 = esl_zext<32,8>(buffer_val_0_q0.read());
}

void rozmycie::thread_tmp2_fu_304_p1() {
    tmp2_fu_304_p1 = esl_zext<32,8>(buffer_val_1_q0.read());
}

void rozmycie::thread_tmp3_fu_533_p2() {
    tmp3_fu_533_p2 = (icmp_reg_711.read() & icmp1_reg_750_pp0_iter2_reg.read());
}

void rozmycie::thread_tmp4_fu_537_p2() {
    tmp4_fu_537_p2 = (tmp_reg_706.read() & tmp_4_reg_730_pp0_iter2_reg.read());
}

void rozmycie::thread_tmp5_cast_fu_559_p1() {
    tmp5_cast_fu_559_p1 = esl_zext<16,15>(tmp5_fu_553_p2.read());
}

void rozmycie::thread_tmp5_fu_553_p2() {
    tmp5_fu_553_p2 = (!tmp6_cast_fu_547_p1.read().is_01() || !tmp7_cast_fu_550_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp6_cast_fu_547_p1.read()) + sc_biguint<15>(tmp7_cast_fu_550_p1.read()));
}

void rozmycie::thread_tmp6_cast_fu_547_p1() {
    tmp6_cast_fu_547_p1 = esl_zext<15,14>(tmp6_reg_759.read());
}

void rozmycie::thread_tmp7_cast_fu_550_p1() {
    tmp7_cast_fu_550_p1 = esl_zext<15,14>(tmp7_reg_764.read());
}

void rozmycie::thread_tmp8_fu_569_p2() {
    tmp8_fu_569_p2 = (!tmp9_cast_fu_563_p1.read().is_01() || !tmp10_cast_fu_566_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp9_cast_fu_563_p1.read()) + sc_biguint<16>(tmp10_cast_fu_566_p1.read()));
}

void rozmycie::thread_tmp9_cast_fu_563_p1() {
    tmp9_cast_fu_563_p1 = esl_zext<16,15>(tmp9_reg_769.read());
}

void rozmycie::thread_tmp_12_fu_591_p3() {
    tmp_12_fu_591_p3 = (!or_cond5_fu_541_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond5_fu_541_p2.read()[0].to_bool())? v0_assign_fu_581_p4.read(): ap_const_lv8_0);
}

void rozmycie::thread_tmp_13_fu_273_p4() {
    tmp_13_fu_273_p4 = col_assign_reg_198.read().range(10, 1);
}

void rozmycie::thread_tmp_14_fu_387_p3() {
    tmp_14_fu_387_p3 = esl_concat<8,5>(okno_val_0_0_s_fu_104.read(), ap_const_lv5_0);
}

void rozmycie::thread_tmp_15_fu_413_p3() {
    tmp_15_fu_413_p3 = esl_concat<8,5>(okno_val_1_0_fu_365_p3.read(), ap_const_lv5_0);
}

void rozmycie::thread_tmp_16_fu_439_p3() {
    tmp_16_fu_439_p3 = esl_concat<8,5>(okno_val_1_1_s_fu_116.read(), ap_const_lv5_0);
}

void rozmycie::thread_tmp_17_fu_469_p3() {
    tmp_17_fu_469_p3 = esl_concat<8,5>(okno_val_2_0_s_fu_124.read(), ap_const_lv5_0);
}

void rozmycie::thread_tmp_1_fu_227_p4() {
    tmp_1_fu_227_p4 = i_reg_187.read().range(9, 1);
}

void rozmycie::thread_tmp_2_fu_243_p2() {
    tmp_2_fu_243_p2 = (!i_reg_187.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_187.read() != ap_const_lv10_0);
}

void rozmycie::thread_tmp_4_fu_261_p2() {
    tmp_4_fu_261_p2 = (!col_assign_reg_198.read().is_01() || !ap_const_lv11_500.is_01())? sc_lv<1>(): (sc_biguint<11>(col_assign_reg_198.read()) < sc_biguint<11>(ap_const_lv11_500));
}

void rozmycie::thread_tmp_6_fu_267_p1() {
    tmp_6_fu_267_p1 = esl_zext<64,11>(col_assign_reg_198.read());
}

void rozmycie::thread_tmp_fu_221_p2() {
    tmp_fu_221_p2 = (!i_reg_187.read().is_01() || !ap_const_lv10_2D0.is_01())? sc_lv<1>(): (sc_biguint<10>(i_reg_187.read()) < sc_biguint<10>(ap_const_lv10_2D0));
}

void rozmycie::thread_tmp_s_fu_289_p2() {
    tmp_s_fu_289_p2 = (!col_assign_reg_198.read().is_01() || !ap_const_lv11_0.is_01())? sc_lv<1>(): sc_lv<1>(col_assign_reg_198.read() != ap_const_lv11_0);
}

void rozmycie::thread_v0_assign_fu_581_p4() {
    v0_assign_fu_581_p4 = acc_V_2_2_i_fu_575_p2.read().range(15, 8);
}

void rozmycie::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_209_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_249_p2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_249_p2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

